# -*- coding: utf-8 -*-
"""train_scrap_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dV6hebxQIRz3k7AWnyW3Hk6SKGg1wvO
"""

from google.colab import files
uploaded = files.upload()

# -----------------  TRAIN MODEL IN COLAB -----------------
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import pickle

# 1️⃣  Read the dataset (must already be uploaded)
df = pd.read_csv("scraping_reasons.csv")
print(df.head())

# 2️⃣  Train TF-IDF + Logistic Regression
X = df["text"]
y = df["label"]

vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1, 2))
X_vec = vectorizer.fit_transform(X)

clf = LogisticRegression(max_iter=500)
clf.fit(X_vec, y)

# 3️⃣  Save trained model + vectorizer
with open("nlp_model.pkl", "wb") as f:
    pickle.dump(clf, f)

with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("✅ Model training complete! Files saved:")
!ls -lh nlp_model.pkl tfidf_vectorizer.pkl

from google.colab import files
files.download("nlp_model.pkl")
files.download("tfidf_vectorizer.pkl")

